import { useState } from 'react';
import { BrainCircuit } from 'lucide-react';
import { generatePlan } from './api/coaching';
import { GoalInput } from './components/GoalInput';
import { PlanView } from './components/PlanView';
import type { CoachingPlan } from './api/types';

type State =
  | { stage: 'idle' }
  | { stage: 'loading' }
  | { stage: 'result'; plan: CoachingPlan }
  | { stage: 'error'; message: string };

export default function App() {
  const [state, setState] = useState<State>({ stage: 'idle' });

  const handleSubmit = async (goal: string) => {
    setState({ stage: 'loading' });
    try {
      const plan = await generatePlan(goal);
      setState({ stage: 'result', plan });
    } catch (err) {
      setState({
        stage: 'error',
        message: err instanceof Error ? err.message : 'Something went wrong',
      });
    }
  };

  const handleReset = () => setState({ stage: 'idle' });

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-indigo-50/40 to-violet-50/30">
      <header className="border-b border-slate-200 bg-white/70 backdrop-blur-md sticky top-0 z-40">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center gap-3">
          <div className="w-8 h-8 bg-gradient-to-br from-indigo-500 to-violet-600 rounded-xl flex items-center justify-center shadow-sm">
            <BrainCircuit size={16} className="text-white" />
          </div>
          <div>
            <h1 className="text-sm font-bold text-slate-900 leading-none">GoalCoach</h1>
            <p className="text-xs text-slate-500 mt-0.5">Turn goals into execution plans</p>
          </div>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        {state.stage !== 'result' && (
          <div className="text-center mb-10">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight mb-3">
              What do you want to achieve?
            </h2>
            <p className="text-slate-500 text-base max-w-lg mx-auto">
              Describe any goal. Get a structured, week-by-week execution plan with concrete tasks.
            </p>
          </div>
        )}

        {(state.stage === 'idle' || state.stage === 'loading' || state.stage === 'error') && (
          <GoalInput
            onSubmit={handleSubmit}
            loading={state.stage === 'loading'}
          />
        )}

        {state.stage === 'loading' && (
          <div className="mt-10 flex flex-col items-center gap-3 text-slate-400">
            <div className="w-8 h-8 border-2 border-indigo-200 border-t-indigo-500 rounded-full animate-spin" />
            <p className="text-sm">Building your plan...</p>
          </div>
        )}

        {state.stage === 'error' && (
          <div className="mt-6 max-w-2xl mx-auto px-4 py-3 bg-rose-50 border border-rose-200 rounded-xl text-sm text-rose-600 flex items-center justify-between gap-3">
            <span><span className="font-semibold">Error:</span> {state.message}</span>
            <button
              onClick={handleReset}
              className="text-rose-500 hover:text-rose-700 underline text-xs whitespace-nowrap"
            >
              Try again
            </button>
          </div>
        )}

        {state.stage === 'result' && (
          <PlanView plan={state.plan} onReset={handleReset} />
        )}
      </main>

      <footer className="mt-16 pb-8 text-center">
        <p className="text-xs text-slate-400">
          Plans generated by GPT-4o mini · Focus on execution, not motivation
        </p>
      </footer>
    </div>
  );
}
